#!/usr/bin/env ruby
# encoding: utf-8

require './realtime/base'
require 'statsd-ruby'


module Rocksteady
  module MQ
    #
    #
    module DesignCreatedStatsD
      extend Rocksteady::MQ::Base
      extend self

      @@statsd = Statsd.new('localhost', 8125)

      #
      #   Return true to indicate success.
      #
      def handle msg
        @@statsd.increment('cowper.kit_build')

        true
      end
    end
  end
end


#
#   First param is the process name, second param is the message it listens on
#
Rocksteady::MQ::DesignCreatedStatsD.run('design_created_statsd', Rocksteady::MQ::Base::DesignCreated)
